/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.smekto4ka.ui.panel;

import ru.smekto4ka.service.GamiltonStructuring;
import ru.smekto4ka.service.Structuring;
import ru.smekto4ka.ui.omponent.GamePanel;
import ru.smekto4ka.ui.omponent.MyPanel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import ru.smekto4ka.service.Game;


/**
 * @author smekto4ka
 */
public class StartFrame extends javax.swing.JFrame {


    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
        buildButton.addActionListener(new AbstractAction() {
            public void actionPerformed(ActionEvent e) {

                jScrollPane1.setViewportView(new GamePanel(Integer.parseInt(xSpinner.getValue().toString()),
                        Integer.parseInt(ySpinner.getValue().toString()),
                        Integer.parseInt(sizeSpiner.getValue().toString())));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buildButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        xSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        ySpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        sizeSpiner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        buildButton.setText("���������");
        jPanel2.add(buildButton);

        jLabel2.setText("x");
        jPanel2.add(jLabel2);

        xSpinner.setModel(new javax.swing.SpinnerNumberModel(4, 4, null, 1));
        xSpinner.setToolTipText("x");
        xSpinner.setMinimumSize(new java.awt.Dimension(50, 30));
        xSpinner.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel2.add(xSpinner);

        jLabel3.setText("y");
        jPanel2.add(jLabel3);

        ySpinner.setModel(new javax.swing.SpinnerNumberModel(4, 4, null, 1));
        ySpinner.setToolTipText("y");
        ySpinner.setMinimumSize(new java.awt.Dimension(50, 30));
        ySpinner.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel2.add(ySpinner);

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);

        sizeSpiner.setModel(new javax.swing.SpinnerNumberModel(6, 6, null, 1));
        sizeSpiner.setMinimumSize(new java.awt.Dimension(50, 30));
        sizeSpiner.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel2.add(sizeSpiner);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(200, 250, 200));
        jPanel3.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(jPanel3);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buildButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner sizeSpiner;
    private javax.swing.JSpinner xSpinner;
    private javax.swing.JSpinner ySpinner;
    // End of variables declaration//GEN-END:variables
}
